limit_req_zone $binary_remote_addr zone=mylimit:10m rate=5r/s;

access_log /var/log/nginx/access.log;

server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    # ✅ Block first
    include /etc/nginx/blocked_ips.conf;

    ssl_certificate /etc/nginx/conf.d/nginx.crt;
    ssl_certificate_key /etc/nginx/conf.d/nginx.key;

    location / {
        # ✅ correct zone name
        limit_req zone=mylimit burst=10 nodelay;

        proxy_pass http://backend:5000;

        # ✅ forward IP properly
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}